#!/usr/bin/php

<?php

use CloudCastle\Core\Console\Console;
use CloudCastle\Core\Console\TerminalColor;

const APP = 'CLI';

unset($argv[0]);
$args = [];

foreach ($argv as $argStr) {
    if (($arg = explode('=', trim($argStr))) && count($arg) === 2) {
        $args[$arg[0]] = trim($arg[1], '"');
    } else {
        $args[] = $argStr;
    }
}

try {
    require(__DIR__ . '/App/bootstrap.php');
    
    $console = new Console(...$args);
    $console->run();
} catch (Exception $e) {
    echo TerminalColor::red($e->getMessage()) . PHP_EOL;
}

echo TerminalColor::green(microtime(true) - START_TIME) . PHP_EOL;